version: "2.0"

services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "MEM_LIMIT=256M"
    volumes:
      - "./homelab/unifi-controller/config:/config"
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8443:8443"
      - "6789:6789/tcp"
    restart: always  # start on boot
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: 'stupid-password'
    volumes:
      - './homelab/pihole/etc-pihole/:/etc/pihole/'
      - './homelab/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    cap_add:
      - NET_ADMIN
    restart: always  # start on boot
  sftp:
    image: linuxserver/openssh-server:latest
    container_name: sftp
    environment:
      TZ: 'America/Los_Angeles'
      PUID: '1000'
      PGID: '1000'
      PASSWORD_ACCESS: 'false'
      USER_NAME: 'backup'
      PUBLIC_KEY_FILE: '/ssh/id_ed25519.pub'
    volumes:
      # Manual configuration of /etc/fstab is likely necessary
      - '/media/backup:/home/backup/share'
      - '/home/ubuntu/.ssh/:/ssh/:ro'
      - './homelab/openssh-server/config:/config'
    ports:
      - "7742:2222/tcp"
    restart: always
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --schedule "9 6 * * *"
    restart: always
